formatter: "markdown" # this is required

header-from: "main.tf"

recursive:
  enabled: false

sections:
  hide: []
  show: []

output:
  file: "README.md"
  mode: replace
  template: |-
    {{ .Content }}

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

content: |-
  {{ .Header }}

  ## Contents

  <blockquote><!-- contents:start -->

  - [Requirements](#requirements)
  - [Providers](#providers)
  - [Execution story](#execution-story)
  {{- if .Module.HasModuleCalls }}
  - [Modules](#modules) _(nested and adjacent)_
    {{- range .Module.ModuleCalls }}
    - [{{ .Name }}](#{{ .Name }})
    {{- end }}
  {{- end }}
  {{- if .Module.HasResources }}
  - [Resources](#resources)
    {{- range .Module.Resources }}
      {{- if eq .GetMode "resource" }}
        {{- $spec := split "." .Spec }}
    - _{{$spec._0}}_.[{{ $spec._1 }}](#{{ $spec._0 }}{{ $spec._1 }})
      {{- end -}}
    {{- end -}}
  {{- end }}
  - [Variables](#variables)
  {{- range .Module.Inputs }}
    - [{{ .Name }}](#{{ .Name }}-{{- if .Required -}}required{{- else }}optional{{- end }}) ({{- if .Required -}}**Required**{{- else }}*Optional*{{- end }})
  {{- end }}
  {{- if .Module.HasOutputs }}
  - [Outputs](#outputs)
    {{- range .Module.Outputs }}
    - [{{ .Name }}](#{{ .Name }})
    {{- end -}}
  {{- end}}
  </blockquote><!-- contents:end -->

  {{- if .Module.HasRequirements }}

  ## Requirements
    {{ range .Module.Requirements }}
  ![{{ .Name }}](https://img.shields.io/badge/{{- .Name -}}-{{- .Version.Raw | replace " " "" -}}-{{ printf "%02x%02x%02x" (mod (.Name | adler32sum) 256) (mod (add (.Name | adler32sum) 85) 256) (mod (add (.Name | adler32sum) 170) 256) }}?logo={{ .Name }})
    {{- end }}
  {{- end }}

  {{- if .Module.HasProviders }}

  ## Providers
    {{ range .Module.Providers }}
  ![{{ .Name }}](https://img.shields.io/badge/{{- .Name -}}-{{- .Version.Raw | replace " " "" -}}-{{ printf "%02x%02x%02x" (mod (.Name | adler32sum) 256) (mod (add (.Name | adler32sum) 85) 256) (mod (add (.Name | adler32sum) 170) 256) }})
    {{- end }}
  {{- end }}

  ## Execution story

  Order in which Terraform will create resources (and likely destroy them in reverse order):
  ```
  EXECUTION_STORY_PLACE_HOLDER
  ```
  
  {{- if .Module.HasModuleCalls }}

  ## Modules
    {{ range .Module.ModuleCalls }}
  <blockquote><!-- module:"{{ .Name }}":start -->

  ### `{{ .Name }}`

  {{ .Description.Raw }}
    <table>
      <tr>
        <td>Module location</td>
        <td><code>{{ .Source }}</code></td>
      </tr>
      <tr>
        <td>In file</td>
        <td><a href="./{{ .Position.Filename }}#L{{ .Position.Line }}"><code>{{ .Position.Filename }}#L{{ .Position.Line }}</code></a></td>
      </tr>
      <tr>
        <td colspan="2"><a href="{{ .Source }}/README.md">README.md</a> <em>(experimental)</em></td>
      </tr>
    </table>
  </blockquote><!-- module:"{{ .Name }}":end -->
    {{- end }}
  {{- end }}

  {{- if .Module.HasResources }}

  ## Resources
    {{ range .Module.Resources }}
      {{- if eq .GetMode "resource" }}
        {{- $specs := split "." .Spec }}
  <blockquote><!-- resource:"{{ $specs._0 }}.{{ $specs._1 }}":start -->

  ### _{{ $specs._0 }}_.`{{ $specs._1 }}`
        {{- if .Description.Raw }}

  {{ .Description.Raw }}
        {{- else }}
        {{ end }}
    <table>
      <tr>
        <td>Provider</td>
        <td><code>{{ .ProviderName }} ({{ .ProviderSource }})</code></td>
      </tr>
      <tr>
        <td>In file</td>
        <td><a href="./{{ .Position.Filename }}#L{{ .Position.Line }}"><code>{{ .Position.Filename }}#L{{ .Position.Line }}</code></a></td>
      </tr>
    </table>
  </blockquote><!-- resource:"{{ $specs._0 }}.{{ $specs._1 }}":end -->
      {{- end -}}
    {{- end -}}
  {{- end }}

  {{- if .Module.HasInputs }}

  ## Variables
    {{ range .Module.Inputs }}
  <blockquote><!-- variable:"{{ .Name }}":start -->

  ### `{{ .Name }}` ({{- if .Required -}}**Required**{{- else }}*Optional*{{- end }})

  {{ .Description.Raw }}

  <details style="border-top-color: inherit; border-top-width: 0.1em; border-top-style: solid; padding-top: 0.5em; padding-bottom: 0.5em;">
    <summary>Show more...</summary>

    **Type**:
    ```hcl
    {{ .Type }}
    ```
    {{- if .HasDefault }}
    **Default**:
    ```json
    {{ .GetValue }}
    ```
    {{- end }}
    In file: <a href="./{{ .Position.Filename }}#L{{ .Position.Line }}"><code>{{ .Position.Filename }}#L{{ .Position.Line }}</code></a>

  </details>
  </blockquote><!-- variable:"{{ .Name }}":end -->
    {{- end }}
  {{- end }}

  {{- if .Module.HasOutputs }}

  ## Outputs
    {{ range .Module.Outputs }}
  <blockquote><!-- output:"{{ .Name }}":start -->

  #### `{{ .Name }}`

  {{ .Description.Raw }}

  In file: <a href="./{{ .Position.Filename }}#L{{ .Position.Line }}"><code>{{ .Position.Filename }}#L{{ .Position.Line }}</code></a>
  </blockquote><!-- output:"{{ .Name }}":end -->
    {{- end -}}
  {{- end -}} 
  
  {{ .Footer }}
