persistentVolumeClaim:
  enabled: true

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 192.168.178.33

# dnsmasq:
#   customDnsEntries:
#     - address=/nas/192.168.178.10
 
#   customCnameEntries:
#     - cname=foo.nas,nas

serviceDhcp:
  enabled: false

serviceWeb:
  loadBalancerIP: 192.168.178.252
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.178.252
  mixedService: true
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

admin:
  enabled: true
  password: "abcdef12"