apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: databases
  namespace: databases
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:17-3.5
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;
        - CREATE EXTENSION "uuid-ossp";
        - CREATE EXTENSION pg_stat_statements;
        - CREATE EXTENSION pg_trgm;
        - CREATE EXTENSION btree_gin;
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  startDelay: 180
  stopDelay: 180
  storage:
    size: 5Gi